# Generated by Django 2.2.4 on 2019-11-25 06:26

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75)),
                ('last_name', models.CharField(max_length=75)),
                ('description', models.TextField()),
                ('company', models.CharField(blank=True, max_length=75)),
                ('title', models.CharField(blank=True, max_length=75)),
                ('languages', models.CharField(blank=True, max_length=100)),
                ('github_link', models.URLField(blank=True)),
                ('instagram_link', models.URLField(blank=True)),
                ('linkedin_link', models.URLField(blank=True)),
                ('twitter_link', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('subheading', models.CharField(max_length=125)),
                ('language', models.CharField(choices=[('python', 'Python'), ('go', 'Go'), ('c', 'C'), ('rust', 'Rust'), ('javascript', 'JS'), ('html', 'HTML'), ('processing', 'Processing')], max_length=100)),
                ('category', models.CharField(choices=[('language-essentials', 'Language Essentials'), ('module-showcase', 'Module Showcase'), ('package-showcase', 'Package Showcase'), ('language-overview', 'Language Overview'), ('project-showcase', 'Project Showcase')], max_length=100)),
                ('github_source', models.URLField(default='https://github.com/canadian-coding/posts/tree/master/')),
                ('instagram_link', models.URLField(default='https://www.instagram.com/canadiancoding/')),
                ('content', markdownx.models.MarkdownxField()),
                ('created', models.DateField(blank=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Author')),
            ],
            options={
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
