# Generated by Django 2.2.4 on 2019-11-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20191125_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('contents', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Demo Files',
            },
        ),
        migrations.AddField(
            model_name='posts',
            name='files',
            field=models.ManyToManyField(to='posts.DemoFiles'),
        ),
    ]
