# Generated by Django 2.2.4 on 2019-11-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20191129_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='files',
        ),
        migrations.AddField(
            model_name='demofiles',
            name='posts',
            field=models.ManyToManyField(to='posts.Posts'),
        ),
    ]
