# Generated by Django 2.2.7 on 2019-12-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20191129_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_slug',
            field=models.SlugField(blank=True, default=models.CharField(max_length=75)),
        ),
    ]
