# Generated by Django 2.2.7 on 2019-12-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_posts_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='languages',
        ),
        migrations.AddField(
            model_name='author',
            name='favourite_language',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('go', 'Go'), ('c', 'C'), ('rust', 'Rust'), ('javascript', 'JS'), ('html', 'HTML'), ('processing', 'Processing')], max_length=100),
        ),
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.CharField(choices=[('language-essentials', 'Language Essentials'), ('module-showcase', 'Module Showcase'), ('language-overview', 'Language Overview'), ('project-showcase', 'Project Showcase')], default=1, max_length=100),
        ),
    ]
