# Generated by Django 2.2.7 on 2019-12-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_demofiles_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='favourite_language',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('go', 'Go'), ('c', 'C'), ('rust', 'Rust'), ('javascript', 'JS'), ('html', 'HTML'), ('processing', 'Processing'), ('batch', 'Batch'), ('shell', 'Shell Script')], max_length=100),
        ),
        migrations.AlterField(
            model_name='demofiles',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('go', 'Go'), ('c', 'C'), ('rust', 'Rust'), ('javascript', 'JS'), ('html', 'HTML'), ('processing', 'Processing'), ('batch', 'Batch'), ('shell', 'Shell Script')], max_length=100),
        ),
        migrations.AlterField(
            model_name='posts',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('go', 'Go'), ('c', 'C'), ('rust', 'Rust'), ('javascript', 'JS'), ('html', 'HTML'), ('processing', 'Processing'), ('batch', 'Batch'), ('shell', 'Shell Script')], max_length=100),
        ),
    ]
