# Generated by Django 2.2.7 on 2020-01-11 03:36

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0008_auto_20191203_2314'),
        ('programming_languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('created', models.DateField(blank=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('post_slug', models.SlugField(blank=True, default=models.CharField(max_length=75))),
                ('source_code', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('package_provider', models.URLField(blank=True, help_text='pypi.org, crates.io etc.')),
                ('description', markdownx.models.MarkdownxField()),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='posts.Author')),
                ('languages', models.ManyToManyField(blank=True, to='programming_languages.Language')),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
