# Generated by Django 2.2.4 on 2019-11-26 08:01

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0002_auto_20191125_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=9)),
                ('short_description', models.CharField(max_length=75)),
                ('full_description', markdownx.models.MarkdownxField()),
                ('language', models.CharField(choices=[('python', 'Python'), ('go', 'Go'), ('c', 'C'), ('rust', 'Rust'), ('javascript', 'JS'), ('html', 'HTML'), ('processing', 'Processing')], max_length=100)),
                ('github_link', models.URLField(blank=True)),
                ('youtube_playlist_link', models.URLField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Author')),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=75)),
                ('language', models.CharField(choices=[('python', 'Python'), ('go', 'Go'), ('c', 'C'), ('rust', 'Rust'), ('javascript', 'JS'), ('html', 'HTML'), ('processing', 'Processing')], max_length=100)),
                ('github_link', models.URLField(blank=True)),
                ('youtube_id', models.CharField(blank=True, max_length=11)),
                ('content', markdownx.models.MarkdownxField()),
                ('exercises', markdownx.models.MarkdownxField()),
                ('challenges', markdownx.models.MarkdownxField()),
                ('solutions', markdownx.models.MarkdownxField()),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='posts.Author')),
                ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='courses.Course')),
                ('next_module', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='next', to='courses.Module')),
                ('previous_module', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='previous', to='courses.Module')),
            ],
            options={
                'verbose_name_plural': 'Modules',
            },
        ),
    ]
