# Generated by Django 2.2.4 on 2019-11-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='challenges',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='module',
            name='exercises',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='module',
            name='solutions',
            field=models.TextField(),
        ),
    ]
