# Generated by Django 2.2.7 on 2019-12-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20191129_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='number',
            field=models.IntegerField(default=101),
            preserve_default=False,
        ),
    ]
