# Generated by Django 2.2.7 on 2020-01-10 06:42

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('website', models.URLField(blank=True)),
                ('language_creation', models.DateField()),
                ('used_by', models.CharField(max_length=200)),
                ('resources', markdownx.models.MarkdownxField()),
                ('commenting', markdownx.models.MarkdownxField()),
                ('variables', markdownx.models.MarkdownxField()),
                ('functions', markdownx.models.MarkdownxField()),
                ('running', markdownx.models.MarkdownxField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Typing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', markdownx.models.MarkdownxField()),
                ('languages', models.ManyToManyField(blank=True, to='programming_languages.Language')),
            ],
            options={
                'verbose_name_plural': 'Typing Disciplines',
            },
        ),
        migrations.CreateModel(
            name='Syntax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', markdownx.models.MarkdownxField()),
                ('languages', models.ManyToManyField(blank=True, to='programming_languages.Language')),
            ],
            options={
                'verbose_name_plural': 'Syntax Details',
            },
        ),
        migrations.CreateModel(
            name='Paradigms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', markdownx.models.MarkdownxField()),
                ('languages', models.ManyToManyField(blank=True, to='programming_languages.Language')),
            ],
            options={
                'verbose_name_plural': 'Paradigms',
            },
        ),
    ]
