# Generated by Django 2.2.4 on 2019-09-02 20:07

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('subheading', models.CharField(max_length=125)),
                ('language', models.CharField(choices=[('python', 'Python'), ('go', 'Go'), ('c', 'C'), ('rust', 'Rust'), ('javascript', 'JS'), ('html', 'HTML'), ('processing', 'Processing')], max_length=100)),
                ('category', models.CharField(choices=[('language-essentials', 'Language Essentials'), ('module-showcase', 'Module Showcase'), ('package-showcase', 'Package Showcase'), ('language-overview', 'Language Overview'), ('project-showcase', 'Project Showcase')], max_length=100)),
                ('github_source', models.URLField(default='https://github.com/canadian-coding/posts/tree/master/')),
                ('instagram_link', models.URLField(default='https://www.instagram.com/canadiancoding/')),
                ('content', markdownx.models.MarkdownxField()),
                ('created', models.DateField(blank=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
